//idlc -l c messages.idl

struct JoinRequest
{
    boolean b_dummy;
    char str_name[9];
    char str_identity[32];
    char str_password[65];
};

struct JoinResponse
{
    long int_player_id;

    /*
        >0 = success
         0 = server full
        -1 = name taken
        -2 = identity already logged in
        -3 = wrong password
    */
    char str_name[9];
};

struct Input
{
    long int_player_id;
    char ch_direction;
};

struct Position
{
    long int_player_id;
    long int_x;
    long int_y;
	boolean b_active;
    char str_name[9];
};

struct LeaveRequest
{
    long int_player_id;
    char str_identity[32];
};